apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v2
  namespace: default
  labels:
    app: my-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v2
  template:
    metadata:
      labels:
        app: my-app
        version: v2
    spec:
      containers:
        - name: my-app
          image: nginxdemos/hello:plain-text
          env:
            - name: VERSION
              value: "v2-canary"
          ports:
            - containerPort: 80
